<?php

/**
 * @file
 * Contains league_team.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function league_team_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the league_team module.
    case 'help.page.league_team':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Teams for League Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function league_team_theme() {
  return [
    'league_team' => [
      'template' => 'league_team',
      'render element' => 'children',
    ],
  ];
}
